"""Affine warp segment classes and matrix primitives."""

from fuse_augmentations.affine.matrix import (
    apply_d4_image,
    classify_d4_batch,
    crop_resize_matrix,
    hflip_matrix,
    inv3x3,
    matmul3x3,
    normalize_matrix,
    normalize_matrix_io,
    perspective_from_points,
    perspective_grid,
    rotation_matrix,
    scale_matrix,
    shear_x_matrix,
    shear_y_matrix,
    translate_matrix,
    vflip_matrix,
)
from fuse_augmentations.affine.segment import (
    AlbuFusedAffineSegment,
    AlbuProjectiveSegment,
    CropResizeSegment,
    ExactAffineSegment,
    FusedAffineSegment,
    FusedColorSegment,
    FusedLUTSegment,
    ProjectiveSegment,
    build_segments,
    reorder_aggressive,
    reorder_pointwise,
)

__all__ = [
    "AlbuFusedAffineSegment",
    "AlbuProjectiveSegment",
    "CropResizeSegment",
    "ExactAffineSegment",
    "FusedAffineSegment",
    "FusedColorSegment",
    "FusedLUTSegment",
    "ProjectiveSegment",
    "apply_d4_image",
    "build_segments",
    "classify_d4_batch",
    "crop_resize_matrix",
    "hflip_matrix",
    "inv3x3",
    "matmul3x3",
    "normalize_matrix",
    "normalize_matrix_io",
    "perspective_from_points",
    "perspective_grid",
    "reorder_aggressive",
    "reorder_pointwise",
    "rotation_matrix",
    "scale_matrix",
    "shear_x_matrix",
    "shear_y_matrix",
    "translate_matrix",
    "vflip_matrix",
]
