name: Code formatting

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on: # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches: [main]
  pull_request: {}

env:
  PYTHON_VERSION: "3.10"
  UV_TORCH_BACKEND: cpu

defaults:
  run:
    shell: bash

jobs:
  pre-commit-check:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        # for private repo - first is the checkout step, which needs to use unlimited fetch depth for pushing
        #with:
        #  fetch-depth: 0
      - name: 🐍 Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: 🔑 Compute pre-commit cache key
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      - name: 💾 Cache pre-commit environments
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: 🎨 Run pre-commit
        uses: pre-commit/action@v3.0.1
        # this action also provides an additional behaviour when used in private repositories
        # when configured with a GitHub token, the action will push back fixes to the pull request branch
        #with:
        #  token: ${{ secrets.GITHUB_TOKEN }}

  mypy-check:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
      - name: 🐍 Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: 🐍 Install uv
        uses: astral-sh/setup-uv@v7.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          activate-environment: true
      - name: 📦 Install dependencies
        run: uv pip install -e ".[all]" --group dev
      - name: 🔬 Run mypy
        run: mypy src/
